### ISSUE TITLE
Only seems to work locally - no icon in production (azure - umb 11)

### ISSUE THREAD

**Issue by martinlcp** [Rockerby/Umbraco.BackOfficeEditorView#2]
The icon fails to appear at all in Umbraco 11 in production, Azure.

**Comment by Rockerby** [comment]
Thanks for flagging @martinjgriffiths - let me test this out on Azure.

**Comment by Rockerby** [comment]
Hey @martinjgriffiths - I've pushed release 1.0.2 which has a fix for this. It'd be great to hear some feedback if you try this out.

**Comment by martinlcp** [comment]
@Rockerby that did the trick, working fine now.
